<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-NNH3FRS" failures="2" tests="3" name="Test" time="60.509" errors="0" timestamp="2022-07-27T12:39:34 IST">
  <testcase classname="TestClasses.VerifyUserCanLogin" name="verifyUserCanLogin" time="3.623">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at TestClasses.VerifyUserCanLogin.verifyUserCanLogin(VerifyUserCanLogin.java:59)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- verifyUserCanLogin -->
  <testcase classname="TestClasses.VerifyUserCanAddNewAddress" name="verifyUserCanGoToProfilePage" time="7.625"/>
  <testcase classname="TestClasses.VerifyUserCanAddNewAddress" name="veryUserCanAddAddress" time="5.705">
    <failure type="java.lang.AssertionError" message="expected [5] but found [4]">
      <![CDATA[java.lang.AssertionError: expected [5] but found [4]
at TestClasses.VerifyUserCanAddNewAddress.veryUserCanAddAddress(VerifyUserCanAddNewAddress.java:78)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- veryUserCanAddAddress -->
</testsuite> <!-- Test -->
